// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGDkpcnzfcV0eLKMzycoVBrCYMjphlIJM',
    appId: '1:809027975895:web:b3d16b9aca3916b110ce92',
    messagingSenderId: '809027975895',
    projectId: 'phiapp-i',
    authDomain: 'phiapp-i.firebaseapp.com',
    storageBucket: 'phiapp-i.appspot.com',
    measurementId: 'G-KK0J4L3M9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0xNan-hiZKHfmLjrsUmqOOaVsMG6VdU4',
    appId: '1:809027975895:android:cbb8894897e839ad10ce92',
    messagingSenderId: '809027975895',
    projectId: 'phiapp-i',
    storageBucket: 'phiapp-i.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9fvAcqVZ0I5MZ_GqY7GrXesqB22iwYNI',
    appId: '1:809027975895:ios:711a9dcf1c0ddb3610ce92',
    messagingSenderId: '809027975895',
    projectId: 'phiapp-i',
    storageBucket: 'phiapp-i.appspot.com',
    iosClientId: '809027975895-67m6o2q4so6ib1cra408cjo2gddfg84u.apps.googleusercontent.com',
    iosBundleId: 'com.aerobola.phi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9fvAcqVZ0I5MZ_GqY7GrXesqB22iwYNI',
    appId: '1:809027975895:ios:f06d90786ca2fe7610ce92',
    messagingSenderId: '809027975895',
    projectId: 'phiapp-i',
    storageBucket: 'phiapp-i.appspot.com',
    iosClientId: '809027975895-0aovsa0mi60b5ml3n5f7uf2cpam90qp0.apps.googleusercontent.com',
    iosBundleId: 'com.aerobola.phi.RunnerTests',
  );
}
