// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'offers.freezed.dart';
// optional: Since our Offers class is serializable, we must add this line.
// But if Offers was not serializable, we could skip it.
part 'offers.g.dart';

@freezed
class Offers with _$Offers {
  const factory Offers({
    required String category,
    required String id,
    required double price,
    required String title,
    required String image
  }) = _Offers;

  factory Offers.fromJson(Map<String, Object?> json)
  => _$OffersFromJson(json);
}