// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'offer.freezed.dart';
// optional: Since our Offers class is serializable, we must add this line.
// But if Offers was not serializable, we could skip it.
part 'offer.g.dart';

@freezed
class Offer with _$Offer {
  const factory Offer({
    required double discount,
    required String id,
    required String productId,
    required String image
  }) = _Offer;

  factory Offer.fromJson(Map<String, Object?> json)
  => _$OfferFromJson(json);
}