// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'product.freezed.dart';
// optional: Since our product class is serializable, we must add this line.
// But if product was not serializable, we could skip it.
part 'product.g.dart';

@freezed
class product with _$product {
  const factory product({
    required String firstName,
    required String lastName,
    required int age,
  }) = _product;

  factory product.fromJson(Map<String, Object?> json)
  => _$productFromJson(json);
}